name: Build and Deploy App in Dockers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
  
  deploy:
    runs-on: docker-slave
    needs: build
    steps:
    - name: Run container on self-hosted runner
      if: ${{ github.event_name == 'push' }}
      run: |
        sudo docker stop my-app || true
        sudo docker rm my-app || true
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        sudo docker run -d -p 80:80 --name my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
